#!/usr/bin/env node
// Writes a small synthetic data/enriched.json for local UI development.
// Subjects are fictional so the UI can be eyeballed without burning API calls
// or risking factual claims about real people. Run `npm run enrich` for real
// data — it will overwrite this.
import { writeFile, mkdir } from 'node:fs/promises';

const today = new Date().toISOString().slice(5, 10); // MM-DD for "on this day" testing

const fixture = {
  'science/2024/jan/04/eleanor-hartwell-obituary': {
    id: 'science/2024/jan/04/eleanor-hartwell-obituary',
    url: 'https://www.theguardian.com/',
    headline: 'Eleanor Hartwell obituary',
    published: '2024-01-04',
    byline: 'Robin McKie',
    thumbnail: null,
    wordcount: 920,
    section: 'science',
    name: 'Eleanor Hartwell',
    born: `1931-${today}`,
    died: '2023-12-28',
    field: 'molecular biologist',
    one_line: 'helped map the first crystallographic image of an enzyme active site',
    themes: ['cold-war science', 'women in structural biology', 'Cambridge MRC era'],
    best_quote: {
      text: 'You stare at a smudge of dots for six months and one morning it becomes a hand reaching for a key.',
      speaker: 'Eleanor Hartwell',
    },
    mentions: ['Max Perutz', 'Dorothy Hodgkin', 'John Kendrew'],
    notable_dates: [{ md: '04-25', event: 'structure of DNA published, 1953' }],
    _enriched_at: '2025-01-01T00:00:00Z',
    _model: 'fixture',
  },
  'music/2023/jul/22/raymond-ozanne-obituary': {
    id: 'music/2023/jul/22/raymond-ozanne-obituary',
    url: 'https://www.theguardian.com/',
    headline: 'Raymond Ozanne obituary',
    published: '2023-07-22',
    byline: 'Richard Williams',
    thumbnail: null,
    wordcount: 1080,
    section: 'music',
    name: 'Raymond Ozanne',
    born: '1942-03-19',
    died: `2023-${today}`,
    field: 'jazz pianist',
    one_line: 'tone-poet of the late Soho scene whose left hand barely moved',
    themes: ['British modern jazz', 'Ronnie Scott’s house regulars', 'post-bop minimalism'],
    best_quote: {
      text: 'The note you don’t play is paying the rent for the one you do.',
      speaker: 'Raymond Ozanne',
    },
    mentions: ['Stan Tracey', 'Tubby Hayes', 'Norma Winstone'],
    notable_dates: [],
    _enriched_at: '2025-01-01T00:00:00Z',
    _model: 'fixture',
  },
  'politics/2022/nov/03/margaret-fairhurst-obituary': {
    id: 'politics/2022/nov/03/margaret-fairhurst-obituary',
    url: 'https://www.theguardian.com/',
    headline: 'Margaret Fairhurst obituary',
    published: '2022-11-03',
    byline: 'Julia Langdon',
    thumbnail: null,
    wordcount: 980,
    section: 'politics',
    name: 'Margaret Fairhurst',
    born: '1938-05-09',
    died: '2022-10-21',
    field: 'Labour MP',
    one_line: 'backbench thorn whose 1981 housing-bill rebellion forced a rare ministerial U-turn',
    themes: ['Thatcher-era Labour', 'Greater Manchester politics', 'housing policy'],
    best_quote: {
      text: 'I was never going to be a loyalist. The party is not a church and I am not in it for the hymns.',
      speaker: 'Margaret Fairhurst',
    },
    mentions: ['Michael Foot', 'Barbara Castle', 'Neil Kinnock'],
    notable_dates: [],
    _enriched_at: '2025-01-01T00:00:00Z',
    _model: 'fixture',
  },
  'books/2021/apr/11/peter-stannage-obituary': {
    id: 'books/2021/apr/11/peter-stannage-obituary',
    url: 'https://www.theguardian.com/',
    headline: 'Peter Stannage obituary',
    published: '2021-04-11',
    byline: 'Margaret Drabble',
    thumbnail: null,
    wordcount: 1100,
    section: 'books',
    name: 'Peter Stannage',
    born: '1929-09-30',
    died: '2021-03-29',
    field: 'novelist',
    one_line: 'mid-list chronicler of suburban grief whose late memoir found the readership his fiction did not',
    themes: ['post-war English fiction', 'Hampstead literary set', 'memoir as second act'],
    best_quote: {
      text: 'A novel is a long argument with the kind of person you used to be and would now cross the street to avoid.',
      speaker: 'Peter Stannage',
    },
    mentions: ['Iris Murdoch', 'William Trevor', 'Penelope Fitzgerald'],
    notable_dates: [],
    _enriched_at: '2025-01-01T00:00:00Z',
    _model: 'fixture',
  },
  'sport/2020/feb/15/derek-mckinlay-obituary': {
    id: 'sport/2020/feb/15/derek-mckinlay-obituary',
    url: 'https://www.theguardian.com/',
    headline: 'Derek McKinlay obituary',
    published: '2020-02-15',
    byline: 'Brian Glanville',
    thumbnail: null,
    wordcount: 880,
    section: 'sport',
    name: 'Derek McKinlay',
    born: `1944-${today}`,
    died: '2020-02-01',
    field: 'football journalist',
    one_line: 'Glasgow-born chronicler of the British Isles game whose match notebooks now sit in the National Library',
    themes: ['Fleet Street football writing', 'Scotland Old Firm rivalry', 'pre-Premier League era'],
    best_quote: {
      text: 'A press box is the only place I know where you can be lonely with a hundred other men.',
      speaker: 'Derek McKinlay',
    },
    mentions: ['Hugh McIlvanney', 'Jock Stein', 'Kenny Dalglish'],
    notable_dates: [],
    _enriched_at: '2025-01-01T00:00:00Z',
    _model: 'fixture',
  },
  'lifeandstyle/2019/aug/30/joyce-and-bernard-platt-obituary': {
    id: 'lifeandstyle/2019/aug/30/joyce-and-bernard-platt-obituary',
    url: 'https://www.theguardian.com/',
    headline: 'Other lives: Joyce and Bernard Platt',
    published: '2019-08-30',
    byline: 'Susan Platt',
    thumbnail: null,
    wordcount: 320,
    section: 'lifeandstyle',
    name: 'Joyce and Bernard Platt',
    born: '1928',
    died: '2019',
    field: 'community organisers',
    one_line: 'co-founded a Saturday lunch club in 1972 that fed Stockport pensioners for forty years',
    themes: ['volunteer-run community', 'post-war working class self-help', 'Stockport'],
    best_quote: null,
    mentions: ['Susan Platt'],
    notable_dates: [],
    _enriched_at: '2025-01-01T00:00:00Z',
    _model: 'fixture',
  },
};

await mkdir('data', { recursive: true });
await writeFile('data/enriched.json', JSON.stringify(fixture, null, 2));
console.log(`Wrote ${Object.keys(fixture).length} synthetic records → data/enriched.json (run \`npm run shard\` next).`);
